name: Typo check
on:
  - pull_request
  - workflow_dispatch

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Run Typos
        uses: crate-ci/typos@v1.23.6
